pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Areas/Resource/Models/DataDictionaries/DataDictionaryItemRequestViewModel.cs
namespace PearAdmin.AbpTemplate.Admin.Areas.Resource.Models.DataDictionaries
{
    /// <summary>
    /// 数据字典项请求参数视图模型
    /// </summary>
    public class DataDictionaryItemRequestViewModel
    {
        /// <summary>
        /// 数据字典项Id
        /// </summary>
        public int? Id { get; set; }

        /// <summary>
        /// 数据字典Id
        /// </summary>
        public int? DataDictionaryId { get; set; }

        /// <summary>
        /// 过滤文本
        /// </summary>
        public string FilterText { get; set; }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Areas/Resource/Controllers/DataDictionaryController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.UI;
using Abp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using PearAdmin.AbpTemplate.Resource.DataDictionaries;
using PearAdmin.AbpTemplate.Resource.DataDictionaries.Dto;
using PearAdmin.AbpTemplate.Admin.Controllers;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using PearAdmin.AbpTemplate.Admin.Areas.Resource.Models.DataDictionaries;

namespace PearAdmin.AbpTemplate.Admin.Areas.Resource.Controllers
{
    /// <summary>
    /// 数据字典控制器
    /// </summary>
    [Area("Resource")]
    [AbpMvcAuthorize]
    public class DataDictionaryController : AbpTemplateControllerBase
    {
        private readonly IDataDictionaryAppService _dataDictionaryAppService;

        public DataDictionaryController(IDataDictionaryAppService dataDictionaryAppService)
        {
            _dataDictionaryAppService = dataDictionaryAppService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取数据字典列表
        /// </summary>
        /// <returns></returns>
        [DontWrapResult]
        public JsonResult GetDataDictionaryList()
        {
            var dataDictionaryDtos = _dataDictionaryAppService.GetAllDataDictionary();
            return Json(new ResponseParamListViewModel<DataDictionaryDto>(dataDictionaryDtos.Items));
        }

        /// <summary>
        /// 获取数据字典项列表
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetDataDictionaryItemList(DataDictionaryItemRequestViewModel viewModel)
        {
            var dataDictionaryItemDtos = await _dataDictionaryAppService.GetAllDataDictionaryItem(new GetAllDataDictionaryItemInput()
            {
                DataDictionaryId = viewModel.DataDictionaryId,
                FilterText = viewModel.FilterText
            });

            return Json(new ResponseParamListViewModel<DataDictionaryItemDto>(dataDictionaryItemDtos.Items));
        }

        /// <summary>
        /// 根据字典类型获取字典项
        /// </summary>
        /// <param name="type">字典类型</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> GetDataDictionaryItemListByTypeNames([FromBody]GetDataDictionaryListByTypeNamesInput input)
        {
            var dataDictionaryItemDtos = await _dataDictionaryAppService.GetDataDictionaryListByTypeNames(input);
            return Json(new ResponseParamListViewModel<DataDictionaryDto>(dataDictionaryItemDtos.Items));
        }

        /// <summary>
        /// 创建或更新数据字典项
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<IActionResult> CreateOrUpdateDataDictionaryItem(DataDictionaryItemRequestViewModel viewModel)
        {
            if (!viewModel.DataDictionaryId.HasValue && !viewModel.Id.HasValue)
            {
                throw new UserFriendlyException(L("请求参数有误"));
            }

            var output = await _dataDictionaryAppService.GetDataDictionaryItemForEdit(new NullableIdDto<int>(viewModel.Id));

            if (!viewModel.Id.HasValue)
            {
                output.DataDictionaryId = viewModel.DataDictionaryId.Value;
            }

            return View(output);
        }

        /// <summary>
        /// 创建数据字典项
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> CreateDataDictionaryItem([FromBody]CreateDataDictionaryItemDto input)
        {
            await _dataDictionaryAppService.CreateDataDictionaryItem(input);

            return Json(new ResponseParamViewModel(L("CreateDataDictionaryItemSuccessful")));
        }

        /// <summary>
        /// 更新数据字典项
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> UpdateDataDictionaryItem([FromBody]UpdateDataDictionaryItemDto input)
        {
            await _dataDictionaryAppService.UpdateDataDictionaryItem(input);

            return Json(new ResponseParamViewModel(L("UpdateDataDictionaryItemSuccessful")));
        }

        /// <summary>
        /// 删除数据字典项
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteDataDictionaryItem([FromBody]List<EntityDto<int>> input)
        {
            await _dataDictionaryAppService.DeleteDataDictionaryItem(input);

            return Json(new ResponseParamViewModel(L("DeleteDataDictionaryItemSuccessful")));
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Areas/Resource/Views/DataDictionary/CreateOrUpdateDataDictionaryItem.cshtml
@using Abp.Json
@using PearAdmin.AbpTemplate.Resource.DataDictionaries.Dto
@model DataDictionaryItemDto

<style type="text/css">
        #describe {
            border: 0;
            outline: none;
            width: -webkit-fill-available;
            padding-left:10px;
            padding-top:10px;
           /* background-color: rgba(0, 0, 0, 0);*//*透明背景*/
        }
 </style>
<form class="layui-form" lay-filter="dataDictionaryItem-form" style="padding: 15px 0 0 0;">
    <input type="hidden" name="id" />
    <input type="hidden" name="dataDictionaryId" />
    <div class="layui-form-item">
        <label class="layui-form-label layui-required">代码</label>
        <div class="layui-input-block">
            <input type="text" name="code" lay-verify="required" placeholder="请输入代码" autocomplete="off" class="layui-input @(Model.Id >0 ? "layui-disabled" : "")" @(Model.Id > 0 ? "readonly" : "")>
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label layui-required">名称</label>
        <div class="layui-input-block">
            <input type="text" name="name" lay-verify="required" placeholder="请输入名称" autocomplete="off" class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">描述</label>
        <div class="layui-input-block">
            <textarea type="layui-textarea" rows="5" name="describe" id="describe" placeholder="请输入描述" autocomplete="off"></textarea>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn layui-hide" lay-submit lay-filter="dataDictionaryItem-submit" id="dataDictionaryItem-submit">提交</button>
        </div>
    </div>
</form>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form'], function () {
            var $ = layui.$;
            var abp = layui.abp;
            var form = layui.form;

            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.iframeAuto(index);

            form.val("dataDictionaryItem-form",@Html.Raw(JsonExtensions.ToJsonString(Model, true,false)));
            form.render();

            window.submitForm = function(){
                $("#dataDictionaryItem-submit").click();
            }

            form.on('submit(dataDictionaryItem-submit)', function (data) {
                var waitIndex = parent.layer.load(2);
                abp.ajax({
                    url: "@Url.Action(Model.Id>0 ? "UpdateDataDictionaryItem":"CreateDataDictionaryItem", "DataDictionary", new { area="Resource" })",
                    data: JSON.stringify(data.field),
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200) {
                        data.index = index;
                        let parentWindow = parent.selectedWindow().window;
                        parentWindow.saveCallback(data);
                    }
                }).fail(function (jqXHR) {
                    parent.layer.msg(jqXHR.message, { icon: 5 });
                }).always(function () {
                    parent.layer.close(waitIndex);
                });

                return false;
            });
        });
    </script>
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Areas/Resource/Views/DataDictionary/Index.cshtml
@using PearAdmin.AbpTemplate.Authorization

@section styles{
    <style type="text/css">
        #dataDictionary-tree {
            width: 100% !important;
            height: -webkit-calc(100vh - 130px);
            height: -moz-calc(100vh - 130px);
            height: calc(100vh - 130px);
        }
    </style>
}

<div class="layui-card">
    <div class="layui-card-body">
        <form class="layui-form form-search" action="">
            <div class="layui-form-item">
                <label class="layui-form-label">字典项</label>
                <div class="layui-input-inline">
                    <input type="text" name="filterText" placeholder="" class="layui-input">
                </div>
                <button class="pear-btn pear-btn-md pear-btn-primary" lay-submit lay-filter="dataDictionaryItem-query">
                    <i class="layui-icon layui-icon-search"></i>
                    查询
                </button>
            </div>
        </form>
    </div>
</div>

<div class="layui-row layui-col-space15">
    <div class="layui-col-md3">
        <div class="layui-card">
            <div class="layui-card-body">
                <div id="dataDictionaryContent" style="overflow: auto">
                    <ul id="dataDictionary-tree" class="dtree" data-id="0"></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="layui-col-md9">
        <div class="layui-card">
            <div class="layui-card-body">
                <table id="dataDictionaryItem-table" lay-filter="dataDictionaryItem-table"></table>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="dataDictionaryItem-toolbar">
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_ResourceManagement_DataDictionary_DataDictionaryItem_Delete))
    {
        <button class="pear-btn pear-btn-danger pear-btn-md" lay-event="batchRemove">
            <i class="layui-icon layui-icon-delete"></i>
            删除
        </button>
    }
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_ResourceManagement_DataDictionary_DataDictionaryItem_Create))
    {
        <button class="pear-btn pear-btn-primary pear-btn-md" lay-event="add">
            <i class="layui-icon layui-icon-add-1"></i>
            新增
        </button>
    }
</script>

<script type="text/html" id="dataDictionaryItem-bar">
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_ResourceManagement_DataDictionary_DataDictionaryItem_Update))
    {
        <button class="pear-btn pear-btn-primary pear-btn-sm" lay-event="edit">
            <i class="layui-icon layui-icon-edit"></i>
        </button>
    }
    @if (await PermissionChecker.IsGrantedAsync(AppPermissionNames.Pages_ResourceManagement_DataDictionary_DataDictionaryItem_Delete))
    {
        <button class="pear-btn pear-btn-danger pear-btn-sm" lay-event="remove">
            <i class="layui-icon layui-icon-delete"></i>
        </button>
    }
</script>

@section scripts{
    <script type="text/javascript">
        layui.use(['abp', 'form', 'dtree', 'table'], function () {
            var $ = layui.$;
            var abp = layui.abp;
            var form = layui.form;
            var dtree = layui.dtree;
            var table = layui.table;

            form.on('submit(dataDictionaryItem-query)', function (data) {
                table.reload('dataDictionaryItem-table', {
                    where: data.field
                });
				return false;
			});

            dtree.render({
                elem: "#dataDictionary-tree",
                initLevel: "1",
                line: true,
                ficon: ["1", "-1"],
                icon: ["0", "0"],
                method: 'get',
                url: "@Url.Action("GetDataDictionaryList", "DataDictionary", new { area= "Resource" })",
                response: {
                    message: "msg",
                    statusCode: 200,
                    title: "typeName"
                },
                dataStyle: "layuiStyle"
            });

            dtree.on("node(dataDictionary-tree)", function (obj) {
                table.reload('dataDictionaryItem-table', {
                    where: { "dataDictionaryId": obj.param.nodeId }
                });
			});

            //绑定字典项列表数据
            table.render({
				elem: '#dataDictionaryItem-table',
				url: '@Url.Action("GetDataDictionaryItemList", "DataDictionary", new { area= "Resource" })',
				height: 'full-150',
                page: false,
                parseData: function (res) {
                    return {
                        "code": res.result.code, //解析接口状态
                        "msg": res.result.msg, //解析提示文本
                        "count": res.result.count, //解析数据长度
                        "data": res.result.data //解析数据列表
                    };
                },
                response: {
                    statusCode: 200 //规定成功的状态码，默认：0
                },
				cols: [
				    [{
						    type: 'checkbox'
					    },
					    {
						    title: '代码',
						    field: 'code',
						    align: 'center'
					    },
					    {
						    title: '名称',
						    field: 'name',
						    align: 'center'
					    },
                        {
						    title: '描述',
						    field: 'describe',
						    align: 'center'
					    },
					    {
						    title: '操作',
						    toolbar: '#dataDictionaryItem-bar',
						    align: 'center',
						    width: 130
					    }
				    ]
			    ],
				skin: 'line',
				toolbar: '#dataDictionaryItem-toolbar',
				defaultToolbar: [{
					layEvent: 'refresh',
					icon: 'layui-icon-refresh',
				}, 'filter', 'print', 'exports']
            });

            //字典项列表操作列
            table.on('tool(dataDictionaryItem-table)', function (obj) {
                var data = obj.data;
		        if (obj.event === 'remove') {
                    window.remove([{ "id": data.id }]);
		        } else if(obj.event === 'edit'){
		            window.edit(data);
		        }
		    });

		    table.on('toolbar(dataDictionaryItem-table)', function(obj){
		        if(obj.event === 'add'){
		            window.add();
		        } else if(obj.event === 'refresh'){
		            window.refresh();
		        } else if(obj.event === 'batchRemove'){
                    let checkData = table.checkStatus(obj.config.id).data;
				    if (checkData.length === 0) {
					    parent.layer.msg("未选中数据", {
						    icon: 3,
						    time: 1000
					    });
					    return false;
                    }
                    var ids = checkData.map(function (d) { return { "id": d.id }; });
                    window.remove(ids);
		        }
            });

            window.saveCallback = function (data) {
                parent.layer.close(data.index);
                abp.notify.success(data.msg);
                table.reload("dataDictionaryItem-table");
            }

            window.add = function () {
                let currentNode = dtree.getNowParam("dataDictionary-tree");
                if (currentNode.nodeId == undefined) {
					parent.layer.msg("未选中数据", {
						icon: 3,
						time: 1000
					});
					return false;
                }

				parent.layer.open({
                    type: 2,
                    title: "添加字典项",
                    content: "@Url.Action("CreateOrUpdateDataDictionaryItem", "DataDictionary", new { area="Resource" })" + abp.utils.formatString("?dataDictionaryId={0}", currentNode.nodeId),
                    area: ["500px","265px"],
                    shade: 0.1,
                    btn: ['确定', '取消'],
                    yes: function (index, layero) {
                        parent.window['layui-layer-iframe'+ index].submitForm();
                    }
                });
            }

		    window.edit = function(data){
		        parent.layer.open({
                    type: 2,
                    title: "编辑字典项",
                    content: "@Url.Action("CreateOrUpdateDataDictionaryItem", "DataDictionary", new { area="Resource" })" + abp.utils.formatString("?id={0}", data.id),
                    area: ["500px","265px"],
                    shade: 0.1,
                    btn: ['确定', '取消'],
                    yes: function (index, layero) {
                        parent.window['layui-layer-iframe'+ index].submitForm();
                    }
                });
            }

            window.remove = function (data) {
                parent.layer.confirm('确定删除吗?',{
					icon: 3,
					title: '提示'
                }, function (index) {
                    parent.layer.close(index);
					let waitIndex = parent.layer.load(2);
                    abp.ajax({
                        url: "@Url.Action("DeleteDataDictionaryItem", "DataDictionary", new { area="Resource" })",
                        data: JSON.stringify(data),
                        abpHandleError: false
                    }).done(function (data) {
                        if (data.code == 200) {
                            abp.notify.success(data.msg);
                            table.reload('dataDictionaryItem-table');
                        }
                    }).fail(function (jqXHR) {
                        parent.layer.msg(jqXHR.message, { icon: 5 });
                    }).always(function () {
                        parent.layer.close(waitIndex);
                    });
                });
            }

	        window.refresh = function(param){
		        table.reload('dataDictionaryItem-table');
		    }
        });
    </script>
}