pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Models/Chat/GetPagedSessionViewModel.cs
using Abp.AutoMapper;
using PearAdmin.AbpTemplate.Social.Chat.Dto;
using PearAdmin.AbpTemplate.Admin.Models.Common;

namespace PearAdmin.AbpTemplate.Admin.Models.Chat
{
    /// <summary>
    /// 会话分页模型
    /// </summary>
    [AutoMapTo(typeof(GetPagedSessionInput))]
    public class GetPagedSessionViewModel : PagedViewModel
    {
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using System.Threading.Tasks;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using PearAdmin.AbpTemplate.Social.Chat;
using PearAdmin.AbpTemplate.Social.Chat.Dto;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class ChatController : AbpTemplateControllerBase
    {
        private readonly IChatAppService _chatAppService;

        public ChatController(IChatAppService chatAppService)
        {
            _chatAppService = chatAppService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetChatUserList()
        {
            var chatUserDtos = await _chatAppService.GetAllChatUser();
            return Json(new ResponseParamListViewModel<ChatUserDto>(chatUserDtos.Items));
        }

        public async Task<JsonResult> GetUnreadMessageCount()
        {
            var unreadMessageCount = await _chatAppService.UnreadMessageCount();
            return Json(new ResponseParamSingleViewModel<int>(unreadMessageCount));
        }

        public async Task<JsonResult> GetUserChatMessageList(long userId)
        {
            var userChatMessages = await _chatAppService.GetUserChatMessages(new GetUserChatMessagesInput()
            {
                UserId = userId
            });
            return Json(new ResponseParamListViewModel<ChatMessageDto>(userChatMessages.Items));
        }

        public async Task MarkAllUnreadMessagesOfUserAsRead(long userId)
        {
            await _chatAppService.MarkAllUnreadMessagesOfUserAsRead(new MarkAllUnreadMessagesOfUserAsReadInput()
            {
                UserId = userId
            });
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Extensions;
using Abp.IO.Extensions;
using Abp.UI;
using Microsoft.AspNetCore.Mvc;
using PearAdmin.AbpTemplate.Admin.Helpers;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using PearAdmin.AbpTemplate.Admin.Models.Users;
using PearAdmin.AbpTemplate.Authorization.Users;
using PearAdmin.AbpTemplate.Authorization.Users.Dto;
using PearAdmin.AbpTemplate.Authorization.Users.Profile;
using PearAdmin.AbpTemplate.Authorization.Users.Profile.Dto;
using PearAdmin.AbpTemplate.CommonDto;
using PearAdmin.AbpTemplate.Net.MimeTypes;
using PearAdmin.AbpTemplate.Notifications;
using PearAdmin.AbpTemplate.Notifications.Dto;
using PearAdmin.AbpTemplate.TempFileCaches;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    /// <summary>
    /// 用户控制器
    /// </summary>
    [AbpMvcAuthorize]
    public class UsersController : AbpTemplateControllerBase
    {
        #region 初始化
        private const int MaxProfilePictureSize = 5242880;//5MB

        private readonly IUserAppService _userAppService;
        private readonly IProfileAppService _profileAppService;
        private readonly INotificationAppService _notificationAppService;
        private readonly ITempFileCacheManager _tempFileCacheManager;

        public UsersController(
            IUserAppService userAppService,
            IProfileAppService profileAppService,
            INotificationAppService notificationAppService,
            ITempFileCacheManager tempFileCacheManager)
        {
            _userAppService = userAppService;
            _profileAppService = profileAppService;
            _notificationAppService = notificationAppService;
            _tempFileCacheManager = tempFileCacheManager;
        }
        #endregion

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //获取当前用户id或null,如果没有用户登录，则可以为空
            if (!AbpSession.UserId.HasValue)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        /// <summary>
        /// 根据分页条件获取用户列表
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetUserList(GetPagedUserViewModel viewModel)
        {
            var input = PagedViewModelMapToPagedInputDto<GetPagedUserViewModel, GetPagedUserInput>(viewModel);
            var pagedUserList = await _userAppService.GetPagedUser(input);

            return Json(new ResponseParamPagedViewModel<UserDto>(pagedUserList.TotalCount, pagedUserList.Items));
        }

        /// <summary>
        /// 创建或更新用户
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public async Task<ActionResult> CreateOrUpdateUser(NullableIdDto<long> input)
        {
            var userForEditOutput = await _userAppService.GetUserForEdit(input);

            return View(userForEditOutput);
        }

        /// <summary>
        /// 创建用户
        /// </summary>
        /// <param name="createOrUpdateViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> CreateUser([FromBody]CreateUserDto input)
        {
            await _userAppService.CreateUser(input);

            return Json(new ResponseParamViewModel(L("CreateUserSuccessful")));
        }

        /// <summary>
        /// 更新用户
        /// </summary>
        /// <param name="createOrUpdateViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> UpdateUser([FromBody]UpdateUserDto input)
        {
            await _userAppService.UpdateUser(input);

            return Json(new ResponseParamViewModel(L("UpdateUserSuccessful")));
        }

        /// <summary>
        /// 删除用户
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteUser([FromBody]List<EntityDto<long>> input)
        {
            await _userAppService.DeleteUser(input);

            return Json(new ResponseParamViewModel(L("DeleteUserSuccessful")));
        }

        /// <summary>
        /// 重置密码
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> ResetUserPassword([FromBody]ResetPasswordInput input)
        {
            var success = await _userAppService.ResetPassword(input);
            var msg = success ? L("DeleteUserSuccessful") : L("DeleteUserFailed");
            return Json(new ResponseParamViewModel(msg));
        }

        /// <summary>
        /// 修改密码
        /// </summary>
        /// <returns></returns>
        public ActionResult ChangePassword()
        {
            return View();
        }

        /// <summary>
        /// 修改密码
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> ChangePassword([FromBody]ChangePasswordDto input)
        {
            await _profileAppService.ChangePassword(input);
            return Json(new ResponseParamViewModel(L("ChangePasswordSuccessful")));
        }

        /// <summary>
        /// 通知设置
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> NotificationSetting()
        {
            var notificationSettings = await _notificationAppService.GetNotificationSettings();
            return View(notificationSettings);
        }

        /// <summary>
        /// 更新通知订阅
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> UpdateNotificationSetting([FromBody]UpdateNotificationSettingsInput input)
        {
            await _notificationAppService.UpdateNotificationSettings(input);
            return Json(new ResponseParamViewModel("UpdateNotificationSettingsSuccessful"));
        }

        /// <summary>
        /// 用户信息
        /// </summary>
        /// <returns></returns>
        public ActionResult UserProfile()
        {
            return View();
        }

        public async Task<FileResult> GetProfilePicture()
        {
            var output = await _profileAppService.GetProfilePicture();
            if (output.ProfilePicture.IsNullOrEmpty())
            {
                return GetDefaultProfilePictureInternal();
            }

            return File(Convert.FromBase64String(output.ProfilePicture), MimeTypeNames.ImageJpeg);
        }

        public async Task<FileResult> GetProfilePictureByUser(EntityDto<long> input)
        {
            var output = await _profileAppService.GetProfilePictureByUser(input);
            if (output.ProfilePicture.IsNullOrEmpty())
            {
                return GetDefaultProfilePictureInternal();
            }

            return File(Convert.FromBase64String(output.ProfilePicture), MimeTypeNames.ImageJpeg);
        }

        public FileResult GetDefaultProfilePicture()
        {
            return GetDefaultProfilePictureInternal();
        }

        protected FileResult GetDefaultProfilePictureInternal()
        {
            return File(Path.Combine("images", "avatar.jpg"), MimeTypeNames.ImagePng);
        }

        /// <summary>
        /// 上传头像
        /// </summary>
        /// <returns></returns>
        public ActionResult UploadProfilePicture()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> UploadProfilePicture([FromForm]FileDto input)
        {
            var profilePictureFile = Request.Form.Files.First();

            //Check input
            if (profilePictureFile == null)
            {
                throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
            }

            if (profilePictureFile.Length > MaxProfilePictureSize)
            {
                throw new UserFriendlyException(L("ProfilePicture_Warn_SizeLimit", AbpTemplateApplicationConsts.MaxProfilPictureBytesUserFriendlyValue));
            }

            byte[] fileBytes;
            using (var stream = profilePictureFile.OpenReadStream())
            {
                fileBytes = stream.GetAllBytes();
            }

            if (!ImageFormatExtension.GetRawImageFormat(fileBytes).IsIn(ImageFormat.Jpeg, ImageFormat.Png, ImageFormat.Gif))
            {
                throw new Exception(L("IncorrectImageFormat"));
            }

            await _profileAppService.UpdateProfilePicture(new UpdateProfilePictureInput()
            {
                ImageBytes = fileBytes
            });

            return Json(new ResponseParamViewModel("UpdateProfilePictureSuccessful"));
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Views/Chat/Index.cshtml
<div class="pear-social">
    <div class="pear-social-side">
        <div class="pear-social-avatar">
            <img src="@Url.Action("GetProfilePicture","Users")" />
        </div>
        <div class="pear-social-control">
            <div pear-id="1" class="layui-this layui-icon layui-icon-dialogue"></div>
        </div>
        <div class="pear-social-setting layui-icon layui-icon-slider"></div>
    </div>
    <div class="pear-social-list">
        <div class="pear-social-list-header">
            <input type="text" class="search" />
            <div class="searchBtn layui-icon layui-icon-add-1"></div>
        </div>
        <div class="pear-social-list-body">
            <div class="layui-side-scroll" style="width: 100%;">
                <div pear-id="1" class="body layui-side-scroll session" id="userList"></div>
            </div>
        </div>
    </div>
    <div class="pear-social-body" data-currUserId="">
        <div class="pear-social-body-header">
            <div class="title"></div>
        </div>
        <div class="pear-social-body-content">
            <div class="pear-social-body-content-chat" id="chatContent" style="overflow:auto;">
                <ul class="content"></ul>
            </div>
            <div class="pear-social-body-content-input">
                <div class="pear-social-body-content-input-tool">
                    <a class="layui-icon layui-icon-face-smile"></a>
                    <a class="layui-icon layui-icon-email"></a>
                    <a class="layui-icon layui-icon-dialogue"></a>
                    <a class="layui-icon layui-icon-time"></a>
                </div>
                <textarea id="socalContent"></textarea>
                <button class="pear-btn pear-btn-md pear-social-body-content-input-enter" data-type="send">发 送</button>
            </div>
        </div>
    </div>
</div>

<script id="userTemplate" type="text/html">
    <div class="body-item" data-id="{{ d.id }}" data-name="{{ d.userName }}">
        <img class="body-item-avatar" src="{{ d.userAvatar }}">
        <span class="body-item-name">{{ d.userName }}</span>
        <span class="dot {{d.isOnline?'online':''}}"></span>
        <span class="layui-badge" style="{{ d.unreadMessageCount > 0?'':'display:none;' }}">{{ d.unreadMessageCount > 0?d.unreadMessageCount:''}}</span>
    </div>
</script>

<script id="messageTemplate" type="text/html">
    <li class="{{ d.side==1? 'me':'other' }}">
        <img src="{{ d.userAvatar }}" title="{{ d.userName }}">
        <span>{{ d.message }}</span>
        <div style="clear:both;">
            <label style="font-size:smaller;float:right; margin-right:40px;margin-top:2px;">{{ layui.util.toDateString(d.creationTime, "yyyy/MM/dd HH:mm:ss") }}</label>
        </div>
    </li>
</script>

@section scripts{
    <script src="~/libs/signalr/signalr.js" asp-append-version="true"></script>
    <script type="text/javascript">
        layui.use(['abp', 'table', 'element', 'laytpl', 'abpsignalrclient', 'abpsignalrchat'], function () {
            var $ = layui.$;
            var abp = layui.abp;
            var element = layui.element;
            var laytpl = layui.laytpl;
            var app = layui.abpsignalrchat;

            var userList = {};

            //加载userList
            var loadChatUser = function () {
                abp.ajax({
                    url: "@Url.Action("GetChatUserList", "Chat")",
                    type: "Get",
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code == 200) {
                        layui.each(data.data, function (index, item) {
                            data.data[index].userAvatar = "@Url.Action("GetProfilePictureByUser","Users")" + abp.utils.formatString("?id={0}", data.data[index].id);
                            laytpl(userTemplate.innerHTML).render(data.data[index], function (html) {
                                $("#userList").append(html);
                            });
                        });
                        userList = data.data;
                    }
                }).fail(function (jqXHR) {
                    layer.msg(jqXHR.message, { icon: 5 });
                });
            }
            loadChatUser();

            //加载messageList
            var loadUserChatMessage = function (currUserId) {
                abp.ajax({
                    url: "@Url.Action("GetUserChatMessageList", "Chat")" + abp.utils.formatString("?userId={0}", currUserId),
                    type: "Get",
                    abpHandleError: false
                }).done(function (data) {
                    if (data.code != 200) {
                        return;
                    }

                    layui.each(data.data, function (index, item) {
                        data.data[index].userAvatar = "@Url.Action("GetProfilePictureByUser","Users")" + abp.utils.formatString("?id={0}", data.data[index].side == 1 ? data.data[index].userId : data.data[index].targetUserId);
                        data.data[index].userName = data.data[index].side == 1 ? data.data[index].userId : data.data[index].targetUserId;
                        laytpl(messageTemplate.innerHTML).render(data.data[index], function (html) {
                            $(".pear-social-body-content .content").prepend(html);
                        });
                    });

                    var e = document.getElementById("chatContent");
                    e.scrollTop = e.scrollHeight;
                    //$(".pear-social-body-content-chat").animate({ "scrollTop": $(".pear-social-body-content-chat")[0].scrollHeight }, 0);
                }).fail(function (jqXHR) {
                    layer.msg(jqXHR.message, { icon: 5 });
                });
            }

            //设置未读消息为已读
            var markAllUnreadMessagesOfUserAsRead = function (currUserId) {
                abp.ajax({
                    url: "@Url.Action("MarkAllUnreadMessagesOfUserAsRead", "Chat")" + abp.utils.formatString("?userId={0}", currUserId),
                    type: "Get",
                    abpHandleError: false
                }).fail(function (jqXHR) {
                    layer.msg(jqXHR.message, { icon: 5 });
                });
            };

            //点击菜单，切换菜单项
            $(".pear-social .pear-social-control").on("click", "div", function () {
                var toolId = $(this).attr("pear-id");

                $(".pear-social .body").css({
                    display: "none"
                });
                $(".pear-social .body[pear-id='" + toolId + "']").css({
                    display: "block"
                });

                $(".pear-social .pear-social-control div").removeClass("layui-this");
                $(this).addClass("layui-this");
            });

            //点击用户列表，切换对话
            $(".layui-side-scroll .session").on("click", "div", function () {
                var userId = $(this).attr("data-id");
                var currUserId = $(".pear-social-body").attr("currUserId");

                if (userId == currUserId) {
                    return;
                }

                $(".pear-social-body").attr("currUserId", userId);
                $(".pear-social-body-header .title").text($(this).attr("data-name"));
                $(".pear-social-body-content .content").html("");
                $("#socalContent").html("");

                loadUserChatMessage(userId);
                markAllUnreadMessagesOfUserAsRead(userId);
            });

            //监听消息
            abp.event.on('app.chat.messageReceived', function (message) {
                console.log(message);
                var currUserId = $(".pear-social-body").attr("currUserId");
                if (currUserId != undefined && currUserId == message.targetUserId) {
                    var data = {
                        message: message.message,
                        side: message.side,
                        userAvatar: "@Url.Action("GetProfilePictureByUser","Users")" + abp.utils.formatString("?id={0}", message.side == 1 ? message.userId : message.targetUserId),
                        userName: message.side == 1 ? message.userId : message.targetUserId
                    };
                    laytpl(messageTemplate.innerHTML).render(data, function (html) {
                        $(".pear-social-body-content .content").append(html);
                    });
                    $(".pear-social-body-content-chat").animate({ "scrollTop": $(".pear-social-body-content-chat")[0].scrollHeight }, 400);
                    markAllUnreadMessagesOfUserAsRead(message.targetUserId);
                    return;
                }

                if (message.side != 1) {
                    for(var i = 0;i< userList.length;i++){
                        if(userList[i].id==message.targetUserId) {
                            userList[i].unreadMessageCount += 1;
                            $("[data-id='" + message.targetUserId + "']")
                                .children(".layui-badge")
                                .css("display","inline")
                                .text(userList[i].unreadMessageCount);
                            break;
                        }
                    }
                }
            });

            //监听阅读状态改变
            abp.event.on('app.chat.allUnreadMessagesOfUserRead', function (data) {
                console.log("allUnreadMessagesOfUserRead 0k");
                for(var i = 0;i< userList.length;i++) {
                    if(userList[i].id==data.friend.userId) {
                        userList[i].unreadMessageCount = 0;
                        $("[data-id='" + data.friend.userId + "']")
                            .children(".layui-badge")
                            .css("display","none")
                            .text('');
                        break;
                    }
                }
            });

            //监听用户在线状态改变
            abp.event.on('app.chat.userConnectionStateChanged', function (data) {
                console.log("userConnectionStateChanged Ok");
                var onlineStatusElement = $("[data-id='" + data.friend.userId + "']").children(".dot");
                if(data.isConnected){
                    onlineStatusElement.addClass("online");
                }
                else{
                    onlineStatusElement.removeClass("online");
                }
            });

            //回车发送内容
            $('#socalContent').bind('keypress', function (event) {
                if (event.keyCode == "13") {
                    event.preventDefault();
                    sendMessage();
                }
            });

            //执行发送内容
            window.sendMessage = function () {
                var currUserId = $(".pear-social-body").attr("currUserId");
                if (currUserId == undefined || currUserId == "") {
                    return false;
                }

                var messageContent = $("#socalContent").val();
                if (messageContent == "") {
                    return false;
                }

                app.chat.sendMessage({
                    tenantId: @AbpSession.TenantId,
                    userId: parseInt(currUserId),
                    message: messageContent
                }, function () {
                    $("#socalContent").val("");
                });
            }

            //监听页面主按钮操作
            var active = {
                send: function () {
                    sendMessage();
                }
            };

            //点击事件转发器
            $('.pear-btn').on('click', function () {
                var type = $(this).data('type');
                active[type] ? active[type].call(this) : '';
            });
        });
    </script>
}