pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;
using System.Threading.Tasks;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using PearAdmin.AbpTemplate.Social.Chat;
using PearAdmin.AbpTemplate.Social.Chat.Dto;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class ChatController : AbpTemplateControllerBase
    {
        private readonly IChatAppService _chatAppService;

        public ChatController(IChatAppService chatAppService)
        {
            _chatAppService = chatAppService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> GetChatUserList()
        {
            var chatUserDtos = await _chatAppService.GetAllChatUser();
            return Json(new ResponseParamListViewModel<ChatUserDto>(chatUserDtos.Items));
        }

        public async Task<JsonResult> GetUnreadMessageCount()
        {
            var unreadMessageCount = await _chatAppService.UnreadMessageCount();
            return Json(new ResponseParamSingleViewModel<int>(unreadMessageCount));
        }

        public async Task<JsonResult> GetUserChatMessageList(long userId)
        {
            var userChatMessages = await _chatAppService.GetUserChatMessages(new GetUserChatMessagesInput()
            {
                UserId = userId
            });
            return Json(new ResponseParamListViewModel<ChatMessageDto>(userChatMessages.Items));
        }

        public async Task MarkAllUnreadMessagesOfUserAsRead(long userId)
        {
            await _chatAppService.MarkAllUnreadMessagesOfUserAsRead(new MarkAllUnreadMessagesOfUserAsReadInput()
            {
                UserId = userId
            });
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class HomeController : AbpTemplateControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ChatPanel()
        {
            return View();
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Microsoft.AspNetCore.Mvc;
using PearAdmin.AbpTemplate.Admin.Models.Common;
using PearAdmin.AbpTemplate.Admin.Models.Notifications;
using PearAdmin.AbpTemplate.Notifications;
using PearAdmin.AbpTemplate.Notifications.Dto;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    /// <summary>
    /// 消息管理控制器
    /// </summary>
    [AbpMvcAuthorize]
    public class NotificationsController : AbpTemplateControllerBase
    {
        private readonly INotificationAppService _notificationAppService;

        public NotificationsController(INotificationAppService notificationAppService)
        {
            _notificationAppService = notificationAppService;
        }

        /// <summary>
        /// 首页
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取未读通知数量
        /// </summary>
        /// <returns></returns>
        public async Task<JsonResult> GetUnreadNotificationCount()
        {
            var unreadNotificationCount = await _notificationAppService.UnreadMessageCount();
            return Json(new ResponseParamSingleViewModel<int>(unreadNotificationCount));
        }

        /// <summary>
        /// 根据分页条件获取消息列表
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetUserNotificationList(GetUserNotificationPagedViewModel viewModel)
        {
            var input = PagedViewModelMapToPagedInputDto<GetUserNotificationPagedViewModel, GetUserNotificationsPagedInput>(viewModel);
            var pagedUserNotificationDto = await _notificationAppService.GetPagedUserNotifications(input);

            return Json(new GetNotificationsResultViewModel(pagedUserNotificationDto.TotalCount, pagedUserNotificationDto.UnreadCount, pagedUserNotificationDto.Items));
        }

        /// <summary>
        /// 设置消息记录全部已读
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SetAllNotificationsAsRead()
        {
            await _notificationAppService.SetAllNotificationsAsRead();

            return Json(new ResponseParamViewModel(L("AllNotificationSetAsReadSuccessful")));
        }

        /// <summary>
        /// 设置指定消息记录已读
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SetNotificationsAsRead([FromBody]List<EntityDto<Guid>> input)
        {
            await _notificationAppService.SetNotificationAsRead(input);

            return Json(new ResponseParamViewModel(L("NotificationSetAsReadSuccessful")));
        }

        /// <summary>
        /// 删除消息记录
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> DeleteNotification([FromBody]List<EntityDto<Guid>> input)
        {
            await _notificationAppService.DeleteNotification(input);

            return Json(new ResponseParamViewModel(L("DeleteNotificationSuccessful")));
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Controllers/WorkSpaceController.cs
using Microsoft.AspNetCore.Mvc;
using Abp.AspNetCore.Mvc.Authorization;

namespace PearAdmin.AbpTemplate.Admin.Controllers
{
    [AbpMvcAuthorize]
    public class WorkSpaceController : AbpTemplateControllerBase
    {
        public ActionResult TenantConsole()
        {
            return View();
        }

        public ActionResult HostConsole()
        {
            return View();
        }
    }
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Views/Home/Index.cshtml
@using PearAdmin.AbpTemplate.Admin.Views
@using PearAdmin.AbpTemplate.Admin.Views.Shared.Components.RightNavbarUserArea
@using PearAdmin.AbpTemplate.Admin.Views.Shared.Components.SideBarMenu
@{
    ViewBag.Title = L("HomePage");
    ViewBag.CurrentPageName = AbpTemplatePageName.Home;
}

@section styles{
<link rel="stylesheet" href="~/css/loader.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
}

<!-- 布局框架 -->
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">
            <img class="logo" src="" />
            <span class="title"></span>
        </div>
        <ul class="layui-nav layui-layout-left">
            <li class="collapse layui-nav-item"><a href="#" class="layui-icon layui-icon-shrink-right"></a></li>
            <li class="refresh layui-nav-item"><a href="#" class="layui-icon layui-icon-refresh-1" loading=600></a></li>
        </ul>
        <div id="control" class="layui-layout-control"></div>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item layui-hide-xs">
                <a class="social">
                    <i class="layui-icon layui-icon-dialogue"></i>
                    <span id="headerMessage"></span>
                </a>
            </li>
            <li class="layui-nav-item layui-hide-xs"><a href="#" class="fullScreen layui-icon layui-icon-screen-full"></a></li>
            <li class="layui-nav-item layui-hide-xs"><a href="https://gitee.com/pear-admin/pear-admin-abp" class="layui-icon layui-icon-website"></a></li>
            <li class="layui-nav-item layui-hide-xs">
                <a class="notice">
                    <i class="layui-icon layui-icon-notice"></i>
                    <span id="headerNotice"></span>
                </a>
            </li>
            @await Component.InvokeAsync(typeof(RightNavbarUserAreaViewComponent))
            <li class="layui-nav-item setting"><a href="#" class="layui-icon layui-icon-more-vertical"></a></li>
        </ul>
    </div>
    <div class="layui-side layui-bg-black">
        <div class="layui-logo">
            <img class="logo" src="" />
            <span class="title"></span>
        </div>
        @await Component.InvokeAsync(typeof(SideBarMenuViewComponent))
    </div>
    <div class="layui-body">
        <div id="content"></div>
    </div>

    <!-- 遮盖层 -->
    <div class="pear-cover"></div>
    <!-- 加载动画-->
    <div class="loader-main">
        <div class="loader"></div>
    </div>
</div>
<!-- 移 动 端 便 捷 操 作 -->
<div class="pear-collapsed-pe collapse">
    <a href="#" class="layui-icon layui-icon-shrink-right"></a>
</div>

@section scripts{
<script type="text/javascript">
    layui.use(['admin', 'layer', 'encrypt', 'abp', 'abpsignalrclient', 'abpsignalrchat'], function () {
        var admin = layui.admin;
        var $ = layui.jquery;
        var layer = layui.layer;
        var encrypt = layui.encrypt;
        var abp = layui.abp;
        var currMessageIndex = "";

        var config = {
            logo: {
                title: "PearAdmin Abp",
                image: "/images/logo.png"
            },
            menu: {
                control: false,
                accordion: true,
                collaspe: false,
                async: false,
                select: encrypt.md5("@Url.Action(AbpSession.TenantId.HasValue ? "TenantConsole" : "HostConsole", "WorkSpace")").toUpperCase()
            },
            tab: {
                enable: true,
                keepState: true,
                session: false,
                max: 20,
                index: {
                    id: encrypt.md5("@Url.Action(AbpSession.TenantId.HasValue ? "TenantConsole": "HostConsole", "WorkSpace")").toUpperCase(),
                    href: '@Url.Action(AbpSession.TenantId.HasValue ? "TenantConsole" : "HostConsole", "WorkSpace")',
                    title: "@Html.Raw(L(AbpSession.TenantId.HasValue ? "TenantConsole": "HostConsole"))"
                }
            },
            theme: {
                defaultColor: "3",
                defaultMenu: "dark-theme",
                defaultHeader: "light-theme",
                allowCustom: true,
                banner: false
            },
            colors: [
                {
                    id: "1",
                    color: "#2d8cf0",
                    second: "#ecf5ff"
                },
                {
                    id: "2",
                    color: "#36b368",
                    second: "#f0f9eb"
                },
                {
                    id: "3",
                    color: "#f6ad55",
                    second: "#fdf6ec"
                },
                {
                    id: "4",
                    color: "#f56c6c",
                    second: "#fef0f0"
                },
                {
                    id: "5",
                    color: "3963bc",
                    second: "#ecf5ff"
                },
                {
                    id: "6",
                    color: "#f7cfea",
                    second: "#ecf5ff"
                }
            ],
            other: {
                keepLoad: false,
                autoHead: false,
                footer: false
            },
            header: {
                message: false
            }
        };
        admin.render(config);

        window.selectedWindow = function () {
            return $(".layui-body .layui-tab-content .layui-show")[0].children[0].contentWindow;
        }

        function loadUnreadNotificationCount() {
            abp.ajax({
                url: "@Url.Action("GetUnreadNotificationCount", "Notifications")",
                type: "Get",
                abpHandleError: false
            }).done(function (data) {
                if (data.code == 200 && data.data > 0) {
                    notificationUnread();
                }
            }).fail(function (jqXHR) {
                layer.msg(jqXHR.message, { icon: 5 });
            });
        }

        function loadUnreadMessageCount() {
            abp.ajax({
                url: "@Url.Action("GetUnreadMessageCount", "Chat")",
                type: "Get",
                abpHandleError: false
            }).done(function (data) {
                if (data.code == 200 && data.data > 0) {
                    messageUnread();
                }
            }).fail(function (jqXHR) {
                layer.msg(jqXHR.message, { icon: 5 });
            });
        }

        $(".social").click(function () {
            currMessageIndex = layer.open({
                type: 2,
                title: "传音",
                content: "@Url.Action("Index", "Chat")",
                area: ["1000px","645px"],
                shade: 0.3,
                maxmin: true,
                shadeClose: true,
                resize: true,
                end: function () {
                    currMessageIndex = "";
                }
            });
        });

        $(".notice").click(function () {
            layer.open({
                type: 2,
                title: "消息通知",
                content: "@Url.Action("Index", "Notifications")",
                area: ["800px","600px"],
                shade: 0.1
            });
        });

        abp.event.on('app.chat.messageReceived', function (message) {
            if (currMessageIndex == "") {
                messageUnread();
            }
        });

        abp.event.on('abp.notifications.received', function (userNotification) {
            abp.notifications.showUiNotifyForUserNotification(userNotification);
            notificationUnread();
        });

        function notificationUnread() {
            $("#headerNotice").addClass("layui-badge-dot");
        }

        function messageUnread() {
            $("#headerMessage").addClass("layui-badge-dot");
        }

        var init = function () {
            loadUnreadNotificationCount();
            loadUnreadMessageCount();
        };
        init();
    });
</script>
}

pear-admin-abp/src/PearAdmin.AbpTemplate.Admin/Views/Home/_Layout.cshtml
@using Abp.Configuration.Startup
@using Abp.Web.Mvc.Alerts
@using Abp.Web.Security.AntiForgery
@inject IAbpAntiForgeryManager AbpAntiForgeryManager
@inject IMultiTenancyConfig MultiTenancyConfig
@inject IAlertManager AlertManager
@inject ILanguageManager LanguageManager
@{
    Layout = null;
    AbpAntiForgeryManager.SetCookie(Context);

    var pageTitle = !string.IsNullOrWhiteSpace(ViewBag.Title) ? ViewBag.Title + " / " : "";
    pageTitle += "AbpTemplate";
}

<!DOCTYPE html>
<html lang="@LanguageManager.CurrentLanguage.Name">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@pageTitle</title>
    <link rel="shortcut icon" href="~/images/favicon.ico" asp-append-version="true">
    <link rel="stylesheet" href="~/libs/pear/css/pear.css" asp-append-version="true" />
    <style id="pearadmin-bg-color"></style>
    @RenderSection("styles", required: false)
</head>
<body class="layui-layout-body pear-admin">

    @RenderBody()

    <script src="~/libs/layui/layui.js" asp-append-version="true"></script>
    <script src="~/libs/pear/pear.js" asp-append-version="true"></script>
    <script src="~/libs/signalr/signalr.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>